Repository puppetlabs/puppet-resource_api, pull requests merged in 2019-06, with the labels that each got.

#180 (maint) Add to_hash function to resourceShim for compatibility
  lib/puppet/resource_api/glue.rb
  spec/puppet/resource_api/glue_spec.rb
Labels: bug

#184 (maint) backport minor fixes from master to 1.6.x
  .travis.yml
  Gemfile
  lib/puppet/resource_api/glue.rb
  spec/integration/resource_api_spec.rb
  spec/puppet/resource_api/glue_spec.rb
Labels: bug

#177 (maint) implement `desc`/`docs` fallback
  lib/puppet/resource_api.rb
  spec/puppet/resource_api/base_context_spec.rb
  spec/puppet/resource_api/puppet_context_spec.rb
  spec/puppet/resource_api_spec.rb
Labels: bug

#182 (PUP-9747) Relax validation for bolt
  README.md
  lib/puppet/resource_api/transport.rb
  spec/puppet/resource_api/transport_spec.rb
Labels: bug

#185 (maint) test fixes
  spec/puppet/resource_api/transport_spec.rb
  spec/puppet/resource_api_spec.rb
Labels: maintenance

#186 (maint) Mergeup 1.6.x: FM-7839, desc/docs cleanup
  Gemfile
  lib/puppet/resource_api.rb
  lib/puppet/resource_api/type_definition.rb
  spec/puppet/resource_api/base_context_spec.rb
  spec/puppet/resource_api/base_type_definition_spec.rb
  spec/puppet/resource_api/puppet_context_spec.rb
  spec/puppet/resource_api_spec.rb
Labels: bug, maintenance

#175 (maint) make test order really random
  .rspec
  spec/puppet/resource_api/type_definition_spec.rb
  spec/puppet/resource_api_spec.rb
Labels: maintenance

#188 (FM-8265) Merge branch '1.6.x' into master
  .rspec
  spec/puppet/resource_api/base_type_definition_spec.rb
  spec/puppet/resource_api_spec.rb
Labels: maintenance

#189 (maint) reduce debug noise caused by `feature?`
  lib/puppet/resource_api/type_definition.rb
Labels: maintenance

#193 (maint) test fixes
  .travis.yml
  Rakefile
  spec/puppet/resource_api_spec.rb
  spec/spec_helper.rb
Labels: maintenance

#174 (MODULES-9428) make the composite namevar implementation usable
  Rakefile
  lib/puppet/resource_api.rb
  lib/puppet/resource_api/glue.rb
  lib/puppet/resource_api/simple_provider.rb
  spec/acceptance/composite_namevar_spec.rb
  spec/acceptance/namevar_spec.rb
  spec/fixtures/test_module/lib/puppet/provider/composite_namevar/composite_namevar.rb
  spec/fixtures/test_module/lib/puppet/provider/multiple_namevar/multiple_namevar.rb
  spec/fixtures/test_module/lib/puppet/type/composite_namevar.rb
  spec/integration/resource_api_spec.rb
  spec/puppet/resource_api/glue_spec.rb
  spec/puppet/resource_api/simple_provider_spec.rb
  spec/puppet/resource_api_spec.rb
Labels: bug

#187 (SERVER-2470) list_all_transports implementation for puppetserver
  lib/puppet/resource_api/transport.rb
  spec/integration/resource_api/transport_spec.rb
  spec/puppet/resource_api/transport_spec.rb
  spec/puppet/resource_api_spec.rb
  spec/spec_helper.rb
Labels: enhancement
