Repository puppetlabs/puppet-resource_api, pull requests merged in 2019-10, with the labels that each got.

#237 (FM-8553) Remove all caching from list_all_transports
  lib/puppet/resource_api/transport.rb
  spec/integration/resource_api/transport_spec.rb
Labels: bug

#238 (FM-8336) Capture and expose attribute ordering from transport schema
  lib/puppet/resource_api/transport.rb
  spec/integration/resource_api/transport_spec.rb
  spec/puppet/resource_api/transport_spec.rb
Labels: enhancement

#239 (packaging) Bump to version '1.8.9'
  lib/puppet/resource_api/version.rb
Labels: maintenance

#181 (FM-8079) Resource API and Transports Hands-on-Lab
  docs/README.md
  docs/hands-on-lab/01-installing-prereqs.md
  docs/hands-on-lab/02-connecting-to-the-lightbulbs-emulator.png
  docs/hands-on-lab/02-connecting-to-the-lightbulbs.md
  docs/hands-on-lab/03-creating-a-new-module.md
  docs/hands-on-lab/03-creating-a-new-module_vscode.png
  docs/hands-on-lab/04-adding-a-new-transport.md
  docs/hands-on-lab/05-implementing-the-transport-hints.md
  docs/hands-on-lab/05-implementing-the-transport.md
  docs/hands-on-lab/06-implementing-the-provider.md
  docs/hands-on-lab/07-implementing-a-task.md
Labels: enhancement
